const elasticsearch = require('@elastic/elasticsearch');

let client = null;

exports.getClient = async(req, res) =>{
    client = new elasticsearch.Client({   
        node: 'http://localhost:9200',
    });

    return res.status(200).send({
        message: "Conectado",
    });
} 

exports.insert = async(req, res) =>{

    const products = [
      {"nome":"Arroz","supermercado": "BH","preco":"5.99"},
{"nome":"Feijão","supermercado": "BH","preco":"3.49"},
{"nome":"Macarrão","supermercado": "BH","preco":"2.99"},
{"nome":"Leite","supermercado": "BH","preco":"4.79"},
{"nome":"Ovos","supermercado": "BH","preco":"2.99"},
{"nome":"Pão","supermercado": "BH","preco":"3.29"},
{"nome":"Manteiga","supermercado": "BH","preco":"5.49"},
{"nome":"Queijo","supermercado": "BH","preco":"6.99"},
{"nome":"Presunto","supermercado": "BH","preco":"7.99"},
{"nome":"Frango","supermercado": "BH","preco":"9.99"},
{"nome":"Carne moída","supermercado": "BH","preco":"12.99"},
{"nome":"Alface","supermercado": "BH","preco":"1.99"},
{"nome":"Tomate","supermercado": "BH","preco":"2.49"},
{"nome":"Cebola","supermercado": "BH","preco":"1.49"},
{"nome":"Batata","supermercado": "BH","preco":"2.29"},
{"nome":"Cenoura","supermercado": "BH","preco":"1.79"},
{"nome":"Banana","supermercado": "BH","preco":"1.99"},
{"nome":"Maçã","supermercado": "BH","preco":"3.49"},
{"nome":"Laranja","supermercado": "BH","preco":"2.99"},
{"nome":"Mamão","supermercado": "BH","preco":"2.79"},
{"nome":"Abacaxi","supermercado": "BH","preco":"4.99"},
{"nome":"Morango","supermercado": "BH","preco":"5.99"},
{"nome":"Melancia","supermercado": "BH","preco":"6.49"},
{"nome":"Suco de laranja","supermercado": "BH","preco":"3.99"},
{"nome":"Refrigerante","supermercado": "BH","preco":"4.49"},
{"nome":"Água mineral","supermercado": "BH","preco":"1.99"},
{"nome":"Café","supermercado": "BH","preco":"6.99"},
{"nome":"Açúcar","supermercado": "BH","preco":"2.49"},
{"nome":"Sal","supermercado": "BH","preco":"1.29"},
{"nome":"Óleo de soja","supermercado": "BH","preco":"4.99"},
{"nome":"Farinha de trigo","supermercado": "BH","preco":"2.99"},
{"nome":"Fermento em pó","supermercado": "BH","preco":"2.49"},
{"nome":"Biscoitos","supermercado": "BH","preco":"3.99"},
{"nome":"Chocolate","supermercado": "BH","preco":"5.49"},
{"nome":"Sorvete","supermercado": "BH","preco":"6.99"},
{"nome":"Cerveja","supermercado": "BH","preco":"3.49"},
{"nome":"Vinho","supermercado": "BH","preco":"12.99"},
{"nome":"Whisky","supermercado": "BH","preco":"39.99"},
{"nome":"Leite condensado","supermercado": "BH","preco":"3.49"},
{"nome":"Creme de leite","supermercado": "BH","preco":"2.99"},
{"nome":"Achocolatado","supermercado": "BH","preco":"4.99"},
{"nome":"Iogurte","supermercado": "BH","preco":"2.49"},
{"nome":"Doce de leite","supermercado": "BH","preco":"4.99"},
{"nome":"Biscoito recheado","supermercado": "BH","preco":"3.99"},
{"nome":"Queijo ralado","supermercado": "BH","preco":"5.99"},
{"nome":"Molho de tomate","supermercado": "BH","preco":"2.99"},
{"nome":"Maionese","supermercado": "BH","preco":"4.49"},
{"nome":"Ketchup","supermercado": "BH","preco":"2.49"},
{"nome":"Mostarda","supermercado": "BH","preco":"2.49"},
{"nome":"Catchup","supermercado": "BH","preco":"2.49"},
{"nome":"Geléia","supermercado": "BH","preco":"3.99"},
{"nome":"Margarina","supermercado": "BH","preco":"2.49"},
{"nome":"Sabonete","supermercado": "BH","preco":"1.99"},
{"nome":"Shampoo","supermercado": "BH","preco":"5.99"},
{"nome":"Condicionador","supermercado": "BH","preco":"5.99"},
{"nome":"Escova de dentes","supermercado": "BH","preco":"3.49"},
{"nome":"Pasta de dente","supermercado": "BH","preco":"2.99"},
{"nome":"Papel higiênico","supermercado": "BH","preco":"4.49"},
{"nome":"Sabão em pó","supermercado": "BH","preco":"6.99"},
{"nome":"Amaciante de roupas","supermercado": "BH","preco":"4.99"},
{"nome":"Detergente","supermercado": "BH","preco":"2.49"},
{"nome":"Esponja de cozinha","supermercado": "BH","preco":"1.99"},
{"nome":"Desodorante","supermercado": "BH","preco":"5.49"},
{"nome":"Perfume","supermercado": "BH","preco":"29.99"},
{"nome":"Talco","supermercado": "BH","preco":"3.49"},
{"nome":"Lâmina de barbear","supermercado": "BH","preco":"4.99"},
{"nome":"Fio dental","supermercado": "BH","preco":"2.49"},
{"nome":"Algodão","supermercado": "BH","preco":"1.99"},
{"nome":"Pilhas","supermercado": "BH","preco":"3.99"},
{"nome":"Lâmpadas","supermercado": "BH","preco":"4.49"},
{"nome":"Vela","supermercado": "BH","preco":"1.99"},
{"nome":"Fósforos","supermercado": "BH","preco":"1.29"},
{"nome":"Enlatados","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinhos","supermercado": "BH","preco":"4.99"},
{"nome":"Pipoca","supermercado": "BH","preco":"2.49"},
{"nome":"Queijo coalho","supermercado": "BH","preco":"7.99"},
{"nome":"Mortadela","supermercado": "BH","preco":"6.99"},
{"nome":"Salsicha","supermercado": "BH","preco":"4.99"},
{"nome":"Linguiça","supermercado": "BH","preco":"5.99"},
{"nome":"Salame","supermercado": "BH","preco":"8.99"},
{"nome":"Peito de peru","supermercado": "BH","preco":"9.99"},
{"nome":"Picanha","supermercado": "BH","preco":"19.99"},
{"nome":"Filé de peixe","supermercado": "BH","preco":"11.99"},
{"nome":"Atum","supermercado": "BH","preco":"5.99"},
{"nome":"Salmão","supermercado": "BH","preco":"14.99"},
{"nome":"Camarão","supermercado": "BH","preco":"16.99"},
{"nome":"Ostras","supermercado": "BH","preco":"19.99"},
{"nome":"Amêndoas","supermercado": "BH","preco":"7.99"},
{"nome":"Castanhas","supermercado": "BH","preco":"9.99"},
{"nome":"Nozes","supermercado": "BH","preco":"8.99"},
{"nome":"Pistaches","supermercado": "BH","preco":"12.99"},
{"nome":"Suco em pó","supermercado": "BH","preco":"1.99"},
{"nome":"Chá","supermercado": "BH","preco":"3.99"},
{"nome":"Massa de pastel","supermercado": "BH","preco":"2.99"},
{"nome":"Molho de pimenta","supermercado": "BH","preco":"2.49"},
{"nome":"Batata chips","supermercado": "BH","preco":"4.99"},
{"nome":"Cereais","supermercado": "BH","preco":"6.99"},
{"nome":"Granola","supermercado": "BH","preco":"5.99"},
{"nome":"Barra de cereal","supermercado": "BH","preco":"2.99"},
{"nome":"Geleia de mocotó","supermercado": "BH","preco":"3.99"},
{"nome":"Feijão preto","supermercado": "BH","preco":"3.49"},
{"nome":"Feijão carioca","supermercado": "BH","preco":"3.49"},
{"nome":"Milho enlatado","supermercado": "BH","preco":"2.99"},
{"nome":"Ervilha enlatada","supermercado": "BH","preco":"2.99"},
{"nome":"Lentilha enlatada","supermercado": "BH","preco":"2.99"},
{"nome":"Amido de milho","supermercado": "BH","preco":"2.99"},
{"nome":"Farinha de mandioca","supermercado": "BH","preco":"2.99"},
{"nome":"Farofa pronta","supermercado": "BH","preco":"3.99"},
{"nome":"Molho shoyu","supermercado": "BH","preco":"3.49"},
{"nome":"Azeite de oliva","supermercado": "BH","preco":"6.99"},
{"nome":"Vinagre","supermercado": "BH","preco":"1.99"},
{"nome":"Azeitonas","supermercado": "BH","preco":"3.99"},
{"nome":"Palmito","supermercado": "BH","preco":"4.99"},
{"nome":"Pepino em conserva","supermercado": "BH","preco":"2.99"},
{"nome":"Abobrinha","supermercado": "BH","preco":"1.99"},
{"nome":"Berinjela","supermercado": "BH","preco":"2.49"},
{"nome":"Repolho","supermercado": "BH","preco":"1.49"},
{"nome":"Milho verde","supermercado": "BH","preco":"2.99"},
{"nome":"Couve-flor","supermercado": "BH","preco":"3.99"},
{"nome":"Brócolis","supermercado": "BH","preco":"3.99"},
{"nome":"Alho","supermercado": "BH","preco":"1.99"},
{"nome":"Salsa","supermercado": "BH","preco":"1.49"},
{"nome":"Hortelã","supermercado": "BH","preco":"1.49"},
{"nome":"Manjericão","supermercado": "BH","preco":"1.99"},
{"nome":"Alecrim","supermercado": "BH","preco":"1.49"},
{"nome":"Salsinha","supermercado": "BH","preco":"1.49"},
{"nome":"Orégano","supermercado": "BH","preco":"1.99"},
{"nome":"Pimenta-do-reino","supermercado": "BH","preco":"2.49"},
{"nome":"Pimenta vermelha","supermercado": "BH","preco":"2.99"},
{"nome":"Mel","supermercado": "BH","preco":"4.99"},
{"nome":"Chocolate em pó","supermercado": "BH","preco":"3.99"},
{"nome":"Gelatina","supermercado": "BH","preco":"1.99"},
{"nome":"Leite em pó","supermercado": "BH","preco":"5.99"},
{"nome":"Cuscuz","supermercado": "BH","preco":"2.99"},
{"nome":"Iogurte de frutas","supermercado": "BH","preco":"2.99"},
{"nome":"Chantilly","supermercado": "BH","preco":"3.49"},
{"nome":"Pudim","supermercado": "BH","preco":"2.99"},
{"nome":"Gelatina em pó","supermercado": "BH","preco":"1.99"},
{"nome":"Bala","supermercado": "BH","preco":"0.99"},
{"nome":"Pipoca doce","supermercado": "BH","preco":"2.99"},
{"nome":"Amendoim","supermercado": "BH","preco":"1.99"},
{"nome":"Salgadinho de milho","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de queijo","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de cebola","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de churrasco","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de bacon","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de pimenta","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de limão","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de salsa","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de alho","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de ervas","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de queijo e cebola","supermercado": "BH","preco":"3.99"},
{"nome":"Salgadinho de presunto e queijo","supermercado": "BH","preco":"3.99"},
{"nome":"Arroz","supermercado": "Carrefour","preco":"6.99"},
{"nome":"Feijão","supermercado": "Carrefour","preco":"4.79"},
{"nome":"Macarrão","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Leite","supermercado": "Carrefour","preco":"5.99"},
{"nome":"Ovos","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Pão","supermercado": "Carrefour","preco":"3.99"},
{"nome":"Manteiga","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Queijo","supermercado": "Carrefour","preco":"8.99"},
{"nome":"Presunto","supermercado": "Carrefour","preco":"9.99"},
{"nome":"Frango","supermercado": "Carrefour","preco":"12.49"},
{"nome":"Carne moída","supermercado": "Carrefour","preco":"15.99"},
{"nome":"Alface","supermercado": "Carrefour","preco":"2.99"},
{"nome":"Tomate","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Cebola","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Batata","supermercado": "Carrefour","preco":"2.99"},
{"nome":"Cenoura","supermercado": "Carrefour","preco":"2.29"},
{"nome":"Banana","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Maçã","supermercado": "Carrefour","preco":"4.49"},
{"nome":"Laranja","supermercado": "Carrefour","preco":"3.99"},
{"nome":"Mamão","supermercado": "Carrefour","preco":"3.29"},
{"nome":"Abacaxi","supermercado": "Carrefour","preco":"5.99"},
{"nome":"Morango","supermercado": "Carrefour","preco":"7.49"},
{"nome":"Melancia","supermercado": "Carrefour","preco":"7.99"},
{"nome":"Suco de laranja","supermercado": "Carrefour","preco":"4.99"},
{"nome":"Refrigerante","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Água mineral","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Café","supermercado": "Carrefour","preco":"7.99"},
{"nome":"Açúcar","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Sal","supermercado": "Carrefour","preco":"1.99"},
{"nome":"Óleo de soja","supermercado": "Carrefour","preco":"5.99"},
{"nome":"Farinha de trigo","supermercado": "Carrefour","preco":"3.99"},
{"nome":"Fermento em pó","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Biscoitos","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Chocolate","supermercado": "Carrefour","preco":"7.49"},
{"nome":"Sorvete","supermercado": "Carrefour","preco":"7.99"},
{"nome":"Cerveja","supermercado": "Carrefour","preco":"4.49"},
{"nome":"Vinho","supermercado": "Carrefour","preco":"14.99"},
{"nome":"Whisky","supermercado": "Carrefour","preco":"49.99"},
{"nome":"Leite condensado","supermercado": "Carrefour","preco":"4.49"},
{"nome":"Creme de leite","supermercado": "Carrefour","preco":"3.99"},
{"nome":"Achocolatado","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Iogurte","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Doce de leite","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Biscoito recheado","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Queijo ralado","supermercado": "Carrefour","preco":"7.49"},
{"nome":"Molho de tomate","supermercado": "Carrefour","preco":"3.99"},
{"nome":"Maionese","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Ketchup","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Mostarda","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Catchup","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Geléia","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Margarina","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Sabonete","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Shampoo","supermercado": "Carrefour","preco":"6.99"},
{"nome":"Condicionador","supermercado": "Carrefour","preco":"6.99"},
{"nome":"Escova de dentes","supermercado": "Carrefour","preco":"4.49"},
{"nome":"Pasta de dente","supermercado": "Carrefour","preco":"3.99"},
{"nome":"Papel higiênico","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Sabão em pó","supermercado": "Carrefour","preco":"8.99"},
{"nome":"Amaciante de roupas","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Detergente","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Esponja de cozinha","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Desodorante","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Perfume","supermercado": "Carrefour","preco":"34.99"},
{"nome":"Talco","supermercado": "Carrefour","preco":"4.49"},
{"nome":"Lâmina de barbear","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Fio dental","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Algodão","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Pilhas","supermercado": "Carrefour","preco":"4.99"},
{"nome":"Lâmpadas","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Vela","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Fósforos","supermercado": "Carrefour","preco":"1.99"},
{"nome":"Enlatados","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinhos","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Pipoca","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Queijo coalho","supermercado": "Carrefour","preco":"10.49"},
{"nome":"Mortadela","supermercado": "Carrefour","preco":"8.99"},
{"nome":"Salsicha","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Linguiça","supermercado": "Carrefour","preco":"7.49"},
{"nome":"Salame","supermercado": "Carrefour","preco":"11.49"},
{"nome":"Peito de peru","supermercado": "Carrefour","preco":"12.99"},
{"nome":"Picanha","supermercado": "Carrefour","preco":"25.99"},
{"nome":"Filé de peixe","supermercado": "Carrefour","preco":"14.49"},
{"nome":"Atum","supermercado": "Carrefour","preco":"6.99"},
{"nome":"Salmão","supermercado": "Carrefour","preco":"17.99"},
{"nome":"Camarão","supermercado": "Carrefour","preco":"19.99"},
{"nome":"Ostras","supermercado": "Carrefour","preco":"22.99"},
{"nome":"Amêndoas","supermercado": "Carrefour","preco":"9.49"},
{"nome":"Castanhas","supermercado": "Carrefour","preco":"11.49"},
{"nome":"Nozes","supermercado": "Carrefour","preco":"10.49"},
{"nome":"Pistaches","supermercado": "Carrefour","preco":"15.99"},
{"nome":"Suco em pó","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Chá","supermercado": "Carrefour","preco":"4.99"},
{"nome":"Massa de pastel","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Molho de pimenta","supermercado": "Carrefour","preco":"2.99"},
{"nome":"Batata chips","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Cereais","supermercado": "Carrefour","preco":"8.49"},
{"nome":"Granola","supermercado": "Carrefour","preco":"7.49"},
{"nome":"Barra de cereal","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Geleia de mocotó","supermercado": "Carrefour","preco":"4.99"},
{"nome":"Feijão preto","supermercado": "Carrefour","preco":"4.79"},
{"nome":"Feijão carioca","supermercado": "Carrefour","preco":"4.79"},
{"nome":"Milho enlatado","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Ervilha enlatada","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Lentilha enlatada","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Amido de milho","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Farinha de mandioca","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Farofa pronta","supermercado": "Carrefour","preco":"4.99"},
{"nome":"Molho shoyu","supermercado": "Carrefour","preco":"4.49"},
{"nome":"Azeite de oliva","supermercado": "Carrefour","preco":"7.99"},
{"nome":"Vinagre","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Azeitonas","supermercado": "Carrefour","preco":"4.99"},
{"nome":"Palmito","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Pepino em conserva","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Abobrinha","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Berinjela","supermercado": "Carrefour","preco":"2.99"},
{"nome":"Repolho","supermercado": "Carrefour","preco":"1.99"},
{"nome":"Milho verde","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Couve-flor","supermercado": "Carrefour","preco":"4.99"},
{"nome":"Brócolis","supermercado": "Carrefour","preco":"4.99"},
{"nome":"Alho","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Salsa","supermercado": "Carrefour","preco":"1.99"},
{"nome":"Hortelã","supermercado": "Carrefour","preco":"1.99"},
{"nome":"Manjericão","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Alecrim","supermercado": "Carrefour","preco":"1.99"},
{"nome":"Salsinha","supermercado": "Carrefour","preco":"1.99"},
{"nome":"Orégano","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Pimenta-do-reino","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Pimenta vermelha","supermercado": "Carrefour","preco":"3.99"},
{"nome":"Mel","supermercado": "Carrefour","preco":"6.49"},
{"nome":"Chocolate em pó","supermercado": "Carrefour","preco":"4.99"},
{"nome":"Gelatina","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Leite em pó","supermercado": "Carrefour","preco":"7.49"},
{"nome":"Cuscuz","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Iogurte de frutas","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Chantilly","supermercado": "Carrefour","preco":"4.49"},
{"nome":"Pudim","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Gelatina em pó","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Bala","supermercado": "Carrefour","preco":"1.49"},
{"nome":"Pipoca doce","supermercado": "Carrefour","preco":"3.49"},
{"nome":"Amendoim","supermercado": "Carrefour","preco":"2.49"},
{"nome":"Salgadinho de milho","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de queijo","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de cebola","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de churrasco","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de bacon","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de pimenta","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de limão","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de salsa","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de alho","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de ervas","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de queijo e cebola","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Salgadinho de presunto e queijo","supermercado": "Carrefour","preco":"5.49"},
{"nome":"Arroz","supermercado": "Epa","preco":"6.59"},
{"nome":"Feijão","supermercado": "Epa","preco":"4.19"},
{"nome":"Macarrão","supermercado": "Epa","preco":"3.89"},
{"nome":"Leite","supermercado": "Epa","preco":"5.29"},
{"nome":"Ovos","supermercado": "Epa","preco":"3.09"},
{"nome":"Pão","supermercado": "Epa","preco":"4.49"},
{"nome":"Manteiga","supermercado": "Epa","preco":"6.79"},
{"nome":"Queijo","supermercado": "Epa","preco":"9.49"},
{"nome":"Presunto","supermercado": "Epa","preco":"10.99"},
{"nome":"Frango","supermercado": "Epa","preco":"13.79"},
{"nome":"Carne moída","supermercado": "Epa","preco":"16.99"},
{"nome":"Alface","supermercado": "Epa","preco":"3.29"},
{"nome":"Tomate","supermercado": "Epa","preco":"3.99"},
{"nome":"Cebola","supermercado": "Epa","preco":"2.69"},
{"nome":"Batata","supermercado": "Epa","preco":"3.19"},
{"nome":"Cenoura","supermercado": "Epa","preco":"2.39"},
{"nome":"Banana","supermercado": "Epa","preco":"2.79"},
{"nome":"Maçã","supermercado": "Epa","preco":"4.19"},
{"nome":"Laranja","supermercado": "Epa","preco":"3.49"},
{"nome":"Mamão","supermercado": "Epa","preco":"3.59"},
{"nome":"Abacaxi","supermercado": "Epa","preco":"5.49"},
{"nome":"Morango","supermercado": "Epa","preco":"7.59"},
{"nome":"Melancia","supermercado": "Epa","preco":"7.99"},
{"nome":"Suco de laranja","supermercado": "Epa","preco":"4.79"},
{"nome":"Refrigerante","supermercado": "Epa","preco":"5.29"},
{"nome":"Água mineral","supermercado": "Epa","preco":"2.19"},
{"nome":"Café","supermercado": "Epa","preco":"7.49"},
{"nome":"Açúcar","supermercado": "Epa","preco":"3.19"},
{"nome":"Sal","supermercado": "Epa","preco":"1.59"},
{"nome":"Óleo de soja","supermercado": "Epa","preco":"6.49"},
{"nome":"Farinha de trigo","supermercado": "Epa","preco":"3.89"},
{"nome":"Fermento em pó","supermercado": "Epa","preco":"3.29"},
{"nome":"Biscoitos","supermercado": "Epa","preco":"5.79"},
{"nome":"Chocolate","supermercado": "Epa","preco":"7.19"},
{"nome":"Sorvete","supermercado": "Epa","preco":"7.49"},
{"nome":"Cerveja","supermercado": "Epa","preco":"4.29"},
{"nome":"Vinho","supermercado": "Epa","preco":"15.99"},
{"nome":"Whisky","supermercado": "Epa","preco":"42.99"},
{"nome":"Leite condensado","supermercado": "Epa","preco":"4.29"},
{"nome":"Creme de leite","supermercado": "Epa","preco":"3.89"},
{"nome":"Achocolatado","supermercado": "Epa","preco":"6.79"},
{"nome":"Iogurte","supermercado": "Epa","preco":"3.29"},
{"nome":"Doce de leite","supermercado": "Epa","preco":"6.79"},
{"nome":"Biscoito recheado","supermercado": "Epa","preco":"5.79"},
{"nome":"Queijo ralado","supermercado": "Epa","preco":"7.99"},
{"nome":"Molho de tomate","supermercado": "Epa","preco":"3.89"},
{"nome":"Maionese","supermercado": "Epa","preco":"5.79"},
{"nome":"Ketchup","supermercado": "Epa","preco":"3.29"},
{"nome":"Mostarda","supermercado": "Epa","preco":"3.29"},
{"nome":"Catchup","supermercado": "Epa","preco":"3.29"},
{"nome":"Geléia","supermercado": "Epa","preco":"5.79"},
{"nome":"Margarina","supermercado": "Epa","preco":"3.29"},
{"nome":"Sabonete","supermercado": "Epa","preco":"2.59"},
{"nome":"Shampoo","supermercado": "Epa","preco":"6.59"},
{"nome":"Condicionador","supermercado": "Epa","preco":"6.59"},
{"nome":"Escova de dentes","supermercado": "Epa","preco":"4.19"},
{"nome":"Pasta de dente","supermercado": "Epa","preco":"3.89"},
{"nome":"Papel higiênico","supermercado": "Epa","preco":"5.79"},
{"nome":"Sabão em pó","supermercado": "Epa","preco":"7.49"},
{"nome":"Amaciante de roupas","supermercado": "Epa","preco":"6.79"},
{"nome":"Detergente","supermercado": "Epa","preco":"3.29"},
{"nome":"Esponja de cozinha","supermercado": "Epa","preco":"2.59"},
{"nome":"Desodorante","supermercado": "Epa","preco":"6.79"},
{"nome":"Perfume","supermercado": "Epa","preco":"36.99"},
{"nome":"Talco","supermercado": "Epa","preco":"4.19"},
{"nome":"Lâmina de barbear","supermercado": "Epa","preco":"6.79"},
{"nome":"Fio dental","supermercado": "Epa","preco":"3.29"},
{"nome":"Algodão","supermercado": "Epa","preco":"2.59"},
{"nome":"Pilhas","supermercado": "Epa","preco":"4.79"},
{"nome":"Lâmpadas","supermercado": "Epa","preco":"5.29"},
{"nome":"Vela","supermercado": "Epa","preco":"2.19"},
{"nome":"Fósforos","supermercado": "Epa","preco":"1.49"},
{"nome":"Enlatados","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinhos","supermercado": "Epa","preco":"6.79"},
{"nome":"Pipoca","supermercado": "Epa","preco":"3.29"},
{"nome":"Queijo coalho","supermercado": "Epa","preco":"11.49"},
{"nome":"Mortadela","supermercado": "Epa","preco":"9.49"},
{"nome":"Salsicha","supermercado": "Epa","preco":"6.79"},
{"nome":"Linguiça","supermercado": "Epa","preco":"7.79"},
{"nome":"Salame","supermercado": "Epa","preco":"12.99"},
{"nome":"Peito de peru","supermercado": "Epa","preco":"13.99"},
{"nome":"Picanha","supermercado": "Epa","preco":"27.99"},
{"nome":"Filé de peixe","supermercado": "Epa","preco":"15.99"},
{"nome":"Atum","supermercado": "Epa","preco":"7.59"},
{"nome":"Salmão","supermercado": "Epa","preco":"19.99"},
{"nome":"Camarão","supermercado": "Epa","preco":"21.99"},
{"nome":"Ostras","supermercado": "Epa","preco":"24.99"},
{"nome":"Amêndoas","supermercado": "Epa","preco":"8.99"},
{"nome":"Castanhas","supermercado": "Epa","preco":"10.99"},
{"nome":"Nozes","supermercado": "Epa","preco":"9.99"},
{"nome":"Pistaches","supermercado": "Epa","preco":"14.99"},
{"nome":"Suco em pó","supermercado": "Epa","preco":"2.59"},
{"nome":"Chá","supermercado": "Epa","preco":"5.79"},
{"nome":"Massa de pastel","supermercado": "Epa","preco":"3.89"},
{"nome":"Molho de pimenta","supermercado": "Epa","preco":"3.29"},
{"nome":"Batata chips","supermercado": "Epa","preco":"6.79"},
{"nome":"Cereais","supermercado": "Epa","preco":"8.79"},
{"nome":"Granola","supermercado": "Epa","preco":"6.79"},
{"nome":"Barra de cereal","supermercado": "Epa","preco":"3.89"},
{"nome":"Geleia de mocotó","supermercado": "Epa","preco":"4.79"},
{"nome":"Feijão preto","supermercado": "Epa","preco":"4.19"},
{"nome":"Feijão carioca","supermercado": "Epa","preco":"4.19"},
{"nome":"Milho enlatado","supermercado": "Epa","preco":"3.89"},
{"nome":"Ervilha enlatada","supermercado": "Epa","preco":"3.89"},
{"nome":"Lentilha enlatada","supermercado": "Epa","preco":"3.89"},
{"nome":"Amido de milho","supermercado": "Epa","preco":"3.89"},
{"nome":"Farinha de mandioca","supermercado": "Epa","preco":"3.89"},
{"nome":"Farofa pronta","supermercado": "Epa","preco":"4.79"},
{"nome":"Molho shoyu","supermercado": "Epa","preco":"4.19"},
{"nome":"Azeite de oliva","supermercado": "Epa","preco":"7.49"},
{"nome":"Vinagre","supermercado": "Epa","preco":"2.59"},
{"nome":"Azeitonas","supermercado": "Epa","preco":"4.79"},
{"nome":"Palmito","supermercado": "Epa","preco":"5.99"},
{"nome":"Pepino em conserva","supermercado": "Epa","preco":"3.89"},
{"nome":"Abobrinha","supermercado": "Epa","preco":"2.59"},
{"nome":"Berinjela","supermercado": "Epa","preco":"3.09"},
{"nome":"Repolho","supermercado": "Epa","preco":"1.79"},
{"nome":"Milho verde","supermercado": "Epa","preco":"3.89"},
{"nome":"Couve-flor","supermercado": "Epa","preco":"4.79"},
{"nome":"Brócolis","supermercado": "Epa","preco":"4.79"},
{"nome":"Alho","supermercado": "Epa","preco":"2.59"},
{"nome":"Salsa","supermercado": "Epa","preco":"1.79"},
{"nome":"Hortelã","supermercado": "Epa","preco":"1.79"},
{"nome":"Manjericão","supermercado": "Epa","preco":"2.59"},
{"nome":"Alecrim","supermercado": "Epa","preco":"1.79"},
{"nome":"Salsinha","supermercado": "Epa","preco":"1.79"},
{"nome":"Orégano","supermercado": "Epa","preco":"2.59"},
{"nome":"Pimenta-do-reino","supermercado": "Epa","preco":"3.29"},
{"nome":"Pimenta vermelha","supermercado": "Epa","preco":"3.89"},
{"nome":"Mel","supermercado": "Epa","preco":"6.79"},
{"nome":"Chocolate em pó","supermercado": "Epa","preco":"4.79"},
{"nome":"Gelatina","supermercado": "Epa","preco":"1.79"},
{"nome":"Leite em pó","supermercado": "Epa","preco":"6.59"},
{"nome":"Cuscuz","supermercado": "Epa","preco":"3.89"},
{"nome":"Iogurte de frutas","supermercado": "Epa","preco":"3.89"},
{"nome":"Chantilly","supermercado": "Epa","preco":"4.19"},
{"nome":"Pudim","supermercado": "Epa","preco":"3.89"},
{"nome":"Gelatina em pó","supermercado": "Epa","preco":"1.79"},
{"nome":"Bala","supermercado": "Epa","preco":"0.89"},
{"nome":"Pipoca doce","supermercado": "Epa","preco":"3.89"},
{"nome":"Amendoim","supermercado": "Epa","preco":"2.59"},
{"nome":"Salgadinho de milho","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de queijo","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de cebola","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de churrasco","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de bacon","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de pimenta","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de limão","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de salsa","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de alho","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de ervas","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de queijo e cebola","supermercado": "Epa","preco":"5.79"},
{"nome":"Salgadinho de presunto e queijo","supermercado": "Epa","preco":"5.79"},
{"nome":"Arroz","supermercado": "Hyper","preco":"8.99"},
{"nome":"Feijão","supermercado": "Hyper","preco":"4.49"},
{"nome":"Macarrão","supermercado": "Hyper","preco":"2.99"},
{"nome":"Leite","supermercado": "Hyper","preco":"5.49"},
{"nome":"Ovos","supermercado": "Hyper","preco":"3.99"},
{"nome":"Pão","supermercado": "Hyper","preco":"3.99"},
{"nome":"Manteiga","supermercado": "Hyper","preco":"6.99"},
{"nome":"Queijo","supermercado": "Hyper","preco":"10.99"},
{"nome":"Presunto","supermercado": "Hyper","preco":"6.49"},
{"nome":"Frango","supermercado": "Hyper","preco":"9.99"},
{"nome":"Carne moída","supermercado": "Hyper","preco":"14.99"},
{"nome":"Alface","supermercado": "Hyper","preco":"1.49"},
{"nome":"Tomate","supermercado": "Hyper","preco":"2.99"},
{"nome":"Cebola","supermercado": "Hyper","preco":"1.29"},
{"nome":"Batata","supermercado": "Hyper","preco":"2.79"},
{"nome":"Cenoura","supermercado": "Hyper","preco":"1.79"},
{"nome":"Banana","supermercado": "Hyper","preco":"1.99"},
{"nome":"Maçã","supermercado": "Hyper","preco":"3.99"},
{"nome":"Laranja","supermercado": "Hyper","preco":"2.49"},
{"nome":"Mamão","supermercado": "Hyper","preco":"2.29"},
{"nome":"Abacaxi","supermercado": "Hyper","preco":"4.99"},
{"nome":"Morango","supermercado": "Hyper","preco":"5.99"},
{"nome":"Melancia","supermercado": "Hyper","preco":"6.49"},
{"nome":"Suco de laranja","supermercado": "Hyper","preco":"3.49"},
{"nome":"Refrigerante","supermercado": "Hyper","preco":"4.49"},
{"nome":"Água mineral","supermercado": "Hyper","preco":"1.49"},
{"nome":"Café","supermercado": "Hyper","preco":"6.99"},
{"nome":"Açúcar","supermercado": "Hyper","preco":"2.49"},
{"nome":"Sal","supermercado": "Hyper","preco":"1.29"},
{"nome":"Óleo de soja","supermercado": "Hyper","preco":"4.99"},
{"nome":"Farinha de trigo","supermercado": "Hyper","preco":"2.99"},
{"nome":"Fermento em pó","supermercado": "Hyper","preco":"2.49"},
{"nome":"Biscoitos","supermercado": "Hyper","preco":"3.99"},
{"nome":"Chocolate","supermercado": "Hyper","preco":"5.49"},
{"nome":"Sorvete","supermercado": "Hyper","preco":"6.99"},
{"nome":"Cerveja","supermercado": "Hyper","preco":"3.49"},
{"nome":"Vinho","supermercado": "Hyper","preco":"12.99"},
{"nome":"Whisky","supermercado": "Hyper","preco":"39.99"},
{"nome":"Leite condensado","supermercado": "Hyper","preco":"3.49"},
{"nome":"Creme de leite","supermercado": "Hyper","preco":"2.99"},
{"nome":"Achocolatado","supermercado": "Hyper","preco":"4.99"},
{"nome":"Iogurte","supermercado": "Hyper","preco":"2.49"},
{"nome":"Doce de leite","supermercado": "Hyper","preco":"4.99"},
{"nome":"Biscoito recheado","supermercado": "Hyper","preco":"3.99"},
{"nome":"Queijo ralado","supermercado": "Hyper","preco":"5.99"},
{"nome":"Molho de tomate","supermercado": "Hyper","preco":"2.99"},
{"nome":"Maionese","supermercado": "Hyper","preco":"4.49"},
{"nome":"Ketchup","supermercado": "Hyper","preco":"2.49"},
{"nome":"Mostarda","supermercado": "Hyper","preco":"2.49"},
{"nome":"Catchup","supermercado": "Hyper","preco":"2.49"},
{"nome":"Geléia","supermercado": "Hyper","preco":"3.99"},
{"nome":"Margarina","supermercado": "Hyper","preco":"2.49"},
{"nome":"Sabonete","supermercado": "Hyper","preco":"1.49"},
{"nome":"Shampoo","supermercado": "Hyper","preco":"5.99"},
{"nome":"Condicionador","supermercado": "Hyper","preco":"5.99"},
{"nome":"Escova de dentes","supermercado": "Hyper","preco":"3.49"},
{"nome":"Pasta de dente","supermercado": "Hyper","preco":"2.99"},
{"nome":"Papel higiênico","supermercado": "Hyper","preco":"4.49"},
{"nome":"Sabão em pó","supermercado": "Hyper","preco":"6.99"},
{"nome":"Amaciante de roupas","supermercado": "Hyper","preco":"4.99"},
{"nome":"Detergente","supermercado": "Hyper","preco":"2.49"},
{"nome":"Esponja de cozinha","supermercado": "Hyper","preco":"1.99"},
{"nome":"Desodorante","supermercado": "Hyper","preco":"5.49"},
{"nome":"Perfume","supermercado": "Hyper","preco":"29.99"},
{"nome":"Talco","supermercado": "Hyper","preco":"3.49"},
{"nome":"Lâmina de barbear","supermercado": "Hyper","preco":"4.99"},
{"nome":"Fio dental","supermercado": "Hyper","preco":"2.49"},
{"nome":"Algodão","supermercado": "Hyper","preco":"1.49"},
{"nome":"Pilhas","supermercado": "Hyper","preco":"3.99"},
{"nome":"Lâmpadas","supermercado": "Hyper","preco":"4.49"},
{"nome":"Vela","supermercado": "Hyper","preco":"1.49"},
{"nome":"Fósforos","supermercado": "Hyper","preco":"1.29"},
{"nome":"Enlatados","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinhos","supermercado": "Hyper","preco":"4.99"},
{"nome":"Pipoca","supermercado": "Hyper","preco":"2.49"},
{"nome":"Queijo coalho","supermercado": "Hyper","preco":"7.99"},
{"nome":"Mortadela","supermercado": "Hyper","preco":"6.99"},
{"nome":"Salsicha","supermercado": "Hyper","preco":"4.99"},
{"nome":"Linguiça","supermercado": "Hyper","preco":"5.99"},
{"nome":"Salame","supermercado": "Hyper","preco":"8.99"},
{"nome":"Peito de peru","supermercado": "Hyper","preco":"9.99"},
{"nome":"Picanha","supermercado": "Hyper","preco":"19.99"},
{"nome":"Filé de peixe","supermercado": "Hyper","preco":"11.99"},
{"nome":"Atum","supermercado": "Hyper","preco":"5.99"},
{"nome":"Salmão","supermercado": "Hyper","preco":"14.99"},
{"nome":"Camarão","supermercado": "Hyper","preco":"16.99"},
{"nome":"Ostras","supermercado": "Hyper","preco":"19.99"},
{"nome":"Amêndoas","supermercado": "Hyper","preco":"7.99"},
{"nome":"Castanhas","supermercado": "Hyper","preco":"9.99"},
{"nome":"Nozes","supermercado": "Hyper","preco":"8.99"},
{"nome":"Pistaches","supermercado": "Hyper","preco":"12.99"},
{"nome":"Suco em pó","supermercado": "Hyper","preco":"1.99"},
{"nome":"Chá","supermercado": "Hyper","preco":"3.99"},
{"nome":"Massa de pastel","supermercado": "Hyper","preco":"2.99"},
{"nome":"Molho de pimenta","supermercado": "Hyper","preco":"2.49"},
{"nome":"Batata chips","supermercado": "Hyper","preco":"4.99"},
{"nome":"Cereais","supermercado": "Hyper","preco":"6.99"},
{"nome":"Granola","supermercado": "Hyper","preco":"5.99"},
{"nome":"Barra de cereal","supermercado": "Hyper","preco":"2.99"},
{"nome":"Geleia de mocotó","supermercado": "Hyper","preco":"3.99"},
{"nome":"Feijão preto","supermercado": "Hyper","preco":"3.49"},
{"nome":"Feijão carioca","supermercado": "Hyper","preco":"3.49"},
{"nome":"Milho enlatado","supermercado": "Hyper","preco":"2.99"},
{"nome":"Ervilha enlatada","supermercado": "Hyper","preco":"2.99"},
{"nome":"Lentilha enlatada","supermercado": "Hyper","preco":"2.99"},
{"nome":"Amido de milho","supermercado": "Hyper","preco":"2.99"},
{"nome":"Farinha de mandioca","supermercado": "Hyper","preco":"2.99"},
{"nome":"Farofa pronta","supermercado": "Hyper","preco":"3.99"},
{"nome":"Molho shoyu","supermercado": "Hyper","preco":"3.49"},
{"nome":"Azeite de oliva","supermercado": "Hyper","preco":"6.99"},
{"nome":"Vinagre","supermercado": "Hyper","preco":"1.99"},
{"nome":"Azeitonas","supermercado": "Hyper","preco":"3.99"},
{"nome":"Palmito","supermercado": "Hyper","preco":"4.99"},
{"nome":"Pepino em conserva","supermercado": "Hyper","preco":"2.99"},
{"nome":"Abobrinha","supermercado": "Hyper","preco":"1.99"},
{"nome":"Berinjela","supermercado": "Hyper","preco":"2.49"},
{"nome":"Repolho","supermercado": "Hyper","preco":"1.49"},
{"nome":"Milho verde","supermercado": "Hyper","preco":"2.99"},
{"nome":"Couve-flor","supermercado": "Hyper","preco":"3.99"},
{"nome":"Brócolis","supermercado": "Hyper","preco":"3.99"},
{"nome":"Alho","supermercado": "Hyper","preco":"1.99"},
{"nome":"Salsa","supermercado": "Hyper","preco":"1.49"},
{"nome":"Hortelã","supermercado": "Hyper","preco":"1.49"},
{"nome":"Manjericão","supermercado": "Hyper","preco":"1.99"},
{"nome":"Alecrim","supermercado": "Hyper","preco":"1.49"},
{"nome":"Salsinha","supermercado": "Hyper","preco":"1.49"},
{"nome":"Orégano","supermercado": "Hyper","preco":"1.99"},
{"nome":"Pimenta-do-reino","supermercado": "Hyper","preco":"2.49"},
{"nome":"Pimenta vermelha","supermercado": "Hyper","preco":"2.99"},
{"nome":"Mel","supermercado": "Hyper","preco":"4.99"},
{"nome":"Chocolate em pó","supermercado": "Hyper","preco":"3.99"},
{"nome":"Gelatina","supermercado": "Hyper","preco":"1.99"},
{"nome":"Leite em pó","supermercado": "Hyper","preco":"5.99"},
{"nome":"Cuscuz","supermercado": "Hyper","preco":"2.99"},
{"nome":"Iogurte de frutas","supermercado": "Hyper","preco":"2.99"},
{"nome":"Chantilly","supermercado": "Hyper","preco":"3.49"},
{"nome":"Pudim","supermercado": "Hyper","preco":"2.99"},
{"nome":"Gelatina em pó","supermercado": "Hyper","preco":"1.99"},
{"nome":"Bala","supermercado": "Hyper","preco":"0.99"},
{"nome":"Pipoca doce","supermercado": "Hyper","preco":"2.99"},
{"nome":"Amendoim","supermercado": "Hyper","preco":"1.99"},
{"nome":"Salgadinho de milho","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de queijo","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de cebola","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de churrasco","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de bacon","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de pimenta","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de limão","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de salsa","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de alho","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de ervas","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de queijo e cebola","supermercado": "Hyper","preco":"3.99"},
{"nome":"Salgadinho de presunto e queijo","supermercado": "Hyper","preco":"5.49"},
{"nome":"Arroz","supermercado": "Bretas","preco":"7.89"},
{"nome":"Feijão","supermercado": "Bretas","preco":"4.29"},
{"nome":"Macarrão","supermercado": "Bretas","preco":"2.79"},
{"nome":"Leite","supermercado": "Bretas","preco":"5.99"},
{"nome":"Ovos","supermercado": "Bretas","preco":"3.49"},
{"nome":"Pão","supermercado": "Bretas","preco":"3.99"},
{"nome":"Manteiga","supermercado": "Bretas","preco":"6.49"},
{"nome":"Queijo","supermercado": "Bretas","preco":"11.99"},
{"nome":"Presunto","supermercado": "Bretas","preco":"5.99"},
{"nome":"Frango","supermercado": "Bretas","preco":"9.49"},
{"nome":"Carne moída","supermercado": "Bretas","preco":"13.99"},
{"nome":"Alface","supermercado": "Bretas","preco":"1.59"},
{"nome":"Tomate","supermercado": "Bretas","preco":"2.99"},
{"nome":"Cebola","supermercado": "Bretas","preco":"1.29"},
{"nome":"Batata","supermercado": "Bretas","preco":"2.99"},
{"nome":"Cenoura","supermercado": "Bretas","preco":"1.99"},
{"nome":"Banana","supermercado": "Bretas","preco":"1.79"},
{"nome":"Maçã","supermercado": "Bretas","preco":"3.99"},
{"nome":"Laranja","supermercado": "Bretas","preco":"2.79"},
{"nome":"Mamão","supermercado": "Bretas","preco":"2.49"},
{"nome":"Abacaxi","supermercado": "Bretas","preco":"4.49"},
{"nome":"Morango","supermercado": "Bretas","preco":"6.99"},
{"nome":"Melancia","supermercado": "Bretas","preco":"7.99"},
{"nome":"Suco de laranja","supermercado": "Bretas","preco":"3.49"},
{"nome":"Refrigerante","supermercado": "Bretas","preco":"4.99"},
{"nome":"Água mineral","supermercado": "Bretas","preco":"1.49"},
{"nome":"Café","supermercado": "Bretas","preco":"6.99"},
{"nome":"Açúcar","supermercado": "Bretas","preco":"2.99"},
{"nome":"Sal","supermercado": "Bretas","preco":"1.29"},
{"nome":"Óleo de soja","supermercado": "Bretas","preco":"4.49"},
{"nome":"Farinha de trigo","supermercado": "Bretas","preco":"2.79"},
{"nome":"Fermento em pó","supermercado": "Bretas","preco":"2.49"},
{"nome":"Biscoitos","supermercado": "Bretas","preco":"3.99"},
{"nome":"Chocolate","supermercado": "Bretas","preco":"5.49"},
{"nome":"Sorvete","supermercado": "Bretas","preco":"6.99"},
{"nome":"Cerveja","supermercado": "Bretas","preco":"4.99"},
{"nome":"Vinho","supermercado": "Bretas","preco":"11.99"},
{"nome":"Whisky","supermercado": "Bretas","preco":"39.99"},
{"nome":"Leite condensado","supermercado": "Bretas","preco":"3.99"},
{"nome":"Creme de leite","supermercado": "Bretas","preco":"2.99"},
{"nome":"Achocolatado","supermercado": "Bretas","preco":"4.49"},
{"nome":"Iogurte","supermercado": "Bretas","preco":"2.79"},
{"nome":"Doce de leite","supermercado": "Bretas","preco":"4.99"},
{"nome":"Biscoito recheado","supermercado": "Bretas","preco":"3.99"},
{"nome":"Queijo ralado","supermercado": "Bretas","preco":"5.99"},
{"nome":"Molho de tomate","supermercado": "Bretas","preco":"2.99"},
{"nome":"Maionese","supermercado": "Bretas","preco":"4.29"},
{"nome":"Ketchup","supermercado": "Bretas","preco":"2.49"},
{"nome":"Mostarda","supermercado": "Bretas","preco":"2.49"},
{"nome":"Catchup","supermercado": "Bretas","preco":"2.49"},
{"nome":"Geléia","supermercado": "Bretas","preco":"3.99"},
{"nome":"Margarina","supermercado": "Bretas","preco":"2.49"},
{"nome":"Sabonete","supermercado": "Bretas","preco":"1.79"},
{"nome":"Shampoo","supermercado": "Bretas","preco":"5.99"},
{"nome":"Condicionador","supermercado": "Bretas","preco":"5.99"},
{"nome":"Escova de dentes","supermercado": "Bretas","preco":"3.49"},
{"nome":"Pasta de dente","supermercado": "Bretas","preco":"2.99"},
{"nome":"Papel higiênico","supermercado": "Bretas","preco":"4.49"},
{"nome":"Sabão em pó","supermercado": "Bretas","preco":"6.99"},
{"nome":"Amaciante de roupas","supermercado": "Bretas","preco":"4.99"},
{"nome":"Detergente","supermercado": "Bretas","preco":"2.49"},
{"nome":"Esponja de cozinha","supermercado": "Bretas","preco":"1.99"},
{"nome":"Desodorante","supermercado": "Bretas","preco":"5.49"},
{"nome":"Perfume","supermercado": "Bretas","preco":"29.99"},
{"nome":"Talco","supermercado": "Bretas","preco":"3.49"},
{"nome":"Lâmina de barbear","supermercado": "Bretas","preco":"4.99"},
{"nome":"Fio dental","supermercado": "Bretas","preco":"2.49"},
{"nome":"Algodão","supermercado": "Bretas","preco":"1.79"},
{"nome":"Pilhas","supermercado": "Bretas","preco":"3.99"},
{"nome":"Lâmpadas","supermercado": "Bretas","preco":"4.49"},
{"nome":"Vela","supermercado": "Bretas","preco":"1.99"},
{"nome":"Fósforos","supermercado": "Bretas","preco":"1.29"},
{"nome":"Enlatados","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinhos","supermercado": "Bretas","preco":"4.99"},
{"nome":"Pipoca","supermercado": "Bretas","preco":"2.99"},
{"nome":"Queijo coalho","supermercado": "Bretas","preco":"7.99"},
{"nome":"Mortadela","supermercado": "Bretas","preco":"6.99"},
{"nome":"Salsicha","supermercado": "Bretas","preco":"4.99"},
{"nome":"Linguiça","supermercado": "Bretas","preco":"5.99"},
{"nome":"Salame","supermercado": "Bretas","preco":"8.99"},
{"nome":"Peito de peru","supermercado": "Bretas","preco":"9.99"},
{"nome":"Picanha","supermercado": "Bretas","preco":"19.99"},
{"nome":"Filé de peixe","supermercado": "Bretas","preco":"11.99"},
{"nome":"Atum","supermercado": "Bretas","preco":"5.99"},
{"nome":"Salmão","supermercado": "Bretas","preco":"14.99"},
{"nome":"Camarão","supermercado": "Bretas","preco":"16.99"},
{"nome":"Ostras","supermercado": "Bretas","preco":"19.99"},
{"nome":"Amêndoas","supermercado": "Bretas","preco":"7.99"},
{"nome":"Castanhas","supermercado": "Bretas","preco":"9.99"},
{"nome":"Nozes","supermercado": "Bretas","preco":"8.99"},
{"nome":"Pistaches","supermercado": "Bretas","preco":"12.99"},
{"nome":"Suco em pó","supermercado": "Bretas","preco":"1.99"},
{"nome":"Chá","supermercado": "Bretas","preco":"3.99"},
{"nome":"Massa de pastel","supermercado": "Bretas","preco":"2.99"},
{"nome":"Molho de pimenta","supermercado": "Bretas","preco":"2.49"},
{"nome":"Batata chips","supermercado": "Bretas","preco":"4.99"},
{"nome":"Cereais","supermercado": "Bretas","preco":"6.99"},
{"nome":"Granola","supermercado": "Bretas","preco":"5.99"},
{"nome":"Barra de cereal","supermercado": "Bretas","preco":"2.99"},
{"nome":"Geleia de mocotó","supermercado": "Bretas","preco":"3.99"},
{"nome":"Feijão preto","supermercado": "Bretas","preco":"3.49"},
{"nome":"Feijão carioca","supermercado": "Bretas","preco":"3.49"},
{"nome":"Milho enlatado","supermercado": "Bretas","preco":"2.99"},
{"nome":"Ervilha enlatada","supermercado": "Bretas","preco":"2.99"},
{"nome":"Lentilha enlatada","supermercado": "Bretas","preco":"2.99"},
{"nome":"Amido de milho","supermercado": "Bretas","preco":"2.99"},
{"nome":"Farinha de mandioca","supermercado": "Bretas","preco":"2.99"},
{"nome":"Farofa pronta","supermercado": "Bretas","preco":"3.99"},
{"nome":"Molho shoyu","supermercado": "Bretas","preco":"3.49"},
{"nome":"Azeite de oliva","supermercado": "Bretas","preco":"6.99"},
{"nome":"Vinagre","supermercado": "Bretas","preco":"1.99"},
{"nome":"Azeitonas","supermercado": "Bretas","preco":"3.99"},
{"nome":"Palmito","supermercado": "Bretas","preco":"4.99"},
{"nome":"Pepino em conserva","supermercado": "Bretas","preco":"2.99"},
{"nome":"Abobrinha","supermercado": "Bretas","preco":"1.99"},
{"nome":"Berinjela","supermercado": "Bretas","preco":"2.49"},
{"nome":"Repolho","supermercado": "Bretas","preco":"1.49"},
{"nome":"Milho verde","supermercado": "Bretas","preco":"2.99"},
{"nome":"Couve-flor","supermercado": "Bretas","preco":"3.99"},
{"nome":"Brócolis","supermercado": "Bretas","preco":"3.99"},
{"nome":"Alho","supermercado": "Bretas","preco":"1.99"},
{"nome":"Salsa","supermercado": "Bretas","preco":"1.49"},
{"nome":"Hortelã","supermercado": "Bretas","preco":"1.49"},
{"nome":"Manjericão","supermercado": "Bretas","preco":"1.99"},
{"nome":"Alecrim","supermercado": "Bretas","preco":"1.49"},
{"nome":"Salsinha","supermercado": "Bretas","preco":"1.49"},
{"nome":"Orégano","supermercado": "Bretas","preco":"1.99"},
{"nome":"Pimenta-do-reino","supermercado": "Bretas","preco":"2.49"},
{"nome":"Pimenta vermelha","supermercado": "Bretas","preco":"2.99"},
{"nome":"Mel","supermercado": "Bretas","preco":"4.99"},
{"nome":"Chocolate em pó","supermercado": "Bretas","preco":"3.99"},
{"nome":"Gelatina","supermercado": "Bretas","preco":"1.99"},
{"nome":"Leite em pó","supermercado": "Bretas","preco":"5.99"},
{"nome":"Cuscuz","supermercado": "Bretas","preco":"2.99"},
{"nome":"Iogurte de frutas","supermercado": "Bretas","preco":"2.99"},
{"nome":"Chantilly","supermercado": "Bretas","preco":"3.49"},
{"nome":"Pudim","supermercado": "Bretas","preco":"2.99"},
{"nome":"Gelatina em pó","supermercado": "Bretas","preco":"1.99"},
{"nome":"Bala","supermercado": "Bretas","preco":"0.99"},
{"nome":"Pipoca doce","supermercado": "Bretas","preco":"2.99"},
{"nome":"Amendoim","supermercado": "Bretas","preco":"1.99"},
{"nome":"Salgadinho de milho","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de queijo","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de cebola","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de churrasco","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de bacon","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de pimenta","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de limão","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de salsa","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de alho","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de ervas","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de queijo e cebola","supermercado": "Bretas","preco":"3.99"},
{"nome":"Salgadinho de presunto e queijo","supermercado": "Bretas","preco":"5.49"},
{"nome":"Arroz","supermercado": "Mart Minas","preco":"6.49"},
{"nome":"Feijão","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Macarrão","supermercado": "Mart Minas","preco":"2.29"},
{"nome":"Leite","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Ovos","supermercado": "Mart Minas","preco":"2.99"},
{"nome":"Pão","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Manteiga","supermercado": "Mart Minas","preco":"5.99"},
{"nome":"Queijo","supermercado": "Mart Minas","preco":"9.99"},
{"nome":"Presunto","supermercado": "Mart Minas","preco":"6.49"},
{"nome":"Frango","supermercado": "Mart Minas","preco":"8.99"},
{"nome":"Carne moída","supermercado": "Mart Minas","preco":"12.99"},
{"nome":"Alface","supermercado": "Mart Minas","preco":"1.29"},
{"nome":"Tomate","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Cebola","supermercado": "Mart Minas","preco":"1.19"},
{"nome":"Batata","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Cenoura","supermercado": "Mart Minas","preco":"1.69"},
{"nome":"Banana","supermercado": "Mart Minas","preco":"1.69"},
{"nome":"Maçã","supermercado": "Mart Minas","preco":"3.29"},
{"nome":"Laranja","supermercado": "Mart Minas","preco":"2.29"},
{"nome":"Mamão","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Abacaxi","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Morango","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Melancia","supermercado": "Mart Minas","preco":"5.99"},
{"nome":"Suco de laranja","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Refrigerante","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Água mineral","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Café","supermercado": "Mart Minas","preco":"5.99"},
{"nome":"Açúcar","supermercado": "Mart Minas","preco":"2.29"},
{"nome":"Sal","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Óleo de soja","supermercado": "Mart Minas","preco":"4.49"},
{"nome":"Farinha de trigo","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Fermento em pó","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Biscoitos","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Chocolate","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Sorvete","supermercado": "Mart Minas","preco":"5.99"},
{"nome":"Cerveja","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Vinho","supermercado": "Mart Minas","preco":"9.99"},
{"nome":"Whisky","supermercado": "Mart Minas","preco":"29.99"},
{"nome":"Leite condensado","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Creme de leite","supermercado": "Mart Minas","preco":"2.99"},
{"nome":"Achocolatado","supermercado": "Mart Minas","preco":"4.49"},
{"nome":"Iogurte","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Doce de leite","supermercado": "Mart Minas","preco":"4.49"},
{"nome":"Biscoito recheado","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Queijo ralado","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Molho de tomate","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Maionese","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Ketchup","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Mostarda","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Catchup","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Geléia","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Margarina","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Sabonete","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Shampoo","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Condicionador","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Escova de dentes","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Pasta de dente","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Papel higiênico","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Sabão em pó","supermercado": "Mart Minas","preco":"5.99"},
{"nome":"Amaciante de roupas","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Detergente","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Esponja de cozinha","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Desodorante","supermercado": "Mart Minas","preco":"4.49"},
{"nome":"Perfume","supermercado": "Mart Minas","preco":"24.99"},
{"nome":"Talco","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Lâmina de barbear","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Fio dental","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Algodão","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Pilhas","supermercado": "Mart Minas","preco":"2.99"},
{"nome":"Lâmpadas","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Vela","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Fósforos","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Enlatados","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinhos","supermercado": "Mart Minas","preco":"4.49"},
{"nome":"Pipoca","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Queijo coalho","supermercado": "Mart Minas","preco":"6.99"},
{"nome":"Mortadela","supermercado": "Mart Minas","preco":"5.99"},
{"nome":"Salsicha","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Linguiça","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Salame","supermercado": "Mart Minas","preco":"7.99"},
{"nome":"Peito de peru","supermercado": "Mart Minas","preco":"8.99"},
{"nome":"Picanha","supermercado": "Mart Minas","preco":"17.99"},
{"nome":"Filé de peixe","supermercado": "Mart Minas","preco":"10.99"},
{"nome":"Atum","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Salmão","supermercado": "Mart Minas","preco":"12.99"},
{"nome":"Camarão","supermercado": "Mart Minas","preco":"14.99"},
{"nome":"Ostras","supermercado": "Mart Minas","preco":"17.99"},
{"nome":"Amêndoas","supermercado": "Mart Minas","preco":"6.99"},
{"nome":"Castanhas","supermercado": "Mart Minas","preco":"8.99"},
{"nome":"Nozes","supermercado": "Mart Minas","preco":"7.99"},
{"nome":"Pistaches","supermercado": "Mart Minas","preco":"11.99"},
{"nome":"Suco em pó","supermercado": "Mart Minas","preco":"1.49"},
{"nome":"Chá","supermercado": "Mart Minas","preco":"2.99"},
{"nome":"Massa de pastel","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Molho de pimenta","supermercado": "Mart Minas","preco":"1.49"},
{"nome":"Batata chips","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Cereais","supermercado": "Mart Minas","preco":"5.49"},
{"nome":"Granola","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Barra de cereal","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Geleia de mocotó","supermercado": "Mart Minas","preco":"2.99"},
{"nome":"Feijão preto","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Feijão carioca","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Milho enlatado","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Ervilha enlatada","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Lentilha enlatada","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Amido de milho","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Farinha de mandioca","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Farofa pronta","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Molho shoyu","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Azeite de oliva","supermercado": "Mart Minas","preco":"5.99"},
{"nome":"Vinagre","supermercado": "Mart Minas","preco":"1.49"},
{"nome":"Azeitonas","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Palmito","supermercado": "Mart Minas","preco":"4.49"},
{"nome":"Pepino em conserva","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Abobrinha","supermercado": "Mart Minas","preco":"1.49"},
{"nome":"Berinjela","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Repolho","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Milho verde","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Couve-flor","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Brócolis","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Alho","supermercado": "Mart Minas","preco":"1.29"},
{"nome":"Salsa","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Hortelã","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Manjericão","supermercado": "Mart Minas","preco":"1.49"},
{"nome":"Alecrim","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Salsinha","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Orégano","supermercado": "Mart Minas","preco":"1.49"},
{"nome":"Pimenta-do-reino","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Pimenta vermelha","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Mel","supermercado": "Mart Minas","preco":"3.99"},
{"nome":"Chocolate em pó","supermercado": "Mart Minas","preco":"2.99"},
{"nome":"Gelatina","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Leite em pó","supermercado": "Mart Minas","preco":"4.99"},
{"nome":"Cuscuz","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Iogurte de frutas","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Chantilly","supermercado": "Mart Minas","preco":"2.99"},
{"nome":"Pudim","supermercado": "Mart Minas","preco":"2.49"},
{"nome":"Gelatina em pó","supermercado": "Mart Minas","preco":"0.99"},
{"nome":"Bala","supermercado": "Mart Minas","preco":"0.49"},
{"nome":"Pipoca doce","supermercado": "Mart Minas","preco":"1.99"},
{"nome":"Amendoim","supermercado": "Mart Minas","preco":"1.49"},
{"nome":"Salgadinho de milho","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de queijo","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de cebola","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de churrasco","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de bacon","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de pimenta","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de limão","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de salsa","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de alho","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de ervas","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de queijo e cebola","supermercado": "Mart Minas","preco":"3.49"},
{"nome":"Salgadinho de presunto e queijo","supermercado": "Mart Minas","preco":"4.49"},
{"nome":"Arroz","supermercado": "Bahamas","preco":"6.71"},
{"nome":"Feijão","supermercado": "Bahamas","preco":"3.59"},
{"nome":"Macarrão","supermercado": "Bahamas","preco":"2.44"},
{"nome":"Leite","supermercado": "Bahamas","preco":"4.88"},
{"nome":"Ovos","supermercado": "Bahamas","preco":"3.29"},
{"nome":"Pão","supermercado": "Bahamas","preco":"3.71"},
{"nome":"Manteiga","supermercado": "Bahamas","preco":"6.39"},
{"nome":"Queijo","supermercado": "Bahamas","preco":"9.29"},
{"nome":"Presunto","supermercado": "Bahamas","preco":"6.24"},
{"nome":"Frango","supermercado": "Bahamas","preco":"8.45"},
{"nome":"Carne moída","supermercado": "Bahamas","preco":"12.06"},
{"nome":"Alface","supermercado": "Bahamas","preco":"1.24"},
{"nome":"Tomate","supermercado": "Bahamas","preco":"2.35"},
{"nome":"Cebola","supermercado": "Bahamas","preco":"1.14"},
{"nome":"Batata","supermercado": "Bahamas","preco":"2.74"},
{"nome":"Cenoura","supermercado": "Bahamas","preco":"1.68"},
{"nome":"Banana","supermercado": "Bahamas","preco":"1.42"},
{"nome":"Maçã","supermercado": "Bahamas","preco":"3.38"},
{"nome":"Laranja","supermercado": "Bahamas","preco":"2.15"},
{"nome":"Mamão","supermercado": "Bahamas","preco":"1.92"},
{"nome":"Abacaxi","supermercado": "Bahamas","preco":"4.05"},
{"nome":"Morango","supermercado": "Bahamas","preco":"4.71"},
{"nome":"Melancia","supermercado": "Bahamas","preco":"6.17"},
{"nome":"Suco de laranja","supermercado": "Bahamas","preco":"3.26"},
{"nome":"Refrigerante","supermercado": "Bahamas","preco":"3.84"},
{"nome":"Água mineral","supermercado": "Bahamas","preco":"1.02"},
{"nome":"Café","supermercado": "Bahamas","preco":"5.59"},
{"nome":"Açúcar","supermercado": "Bahamas","preco":"2.04"},
{"nome":"Sal","supermercado": "Bahamas","preco":"1.02"},
{"nome":"Óleo de soja","supermercado": "Bahamas","preco":"4.62"},
{"nome":"Farinha de trigo","supermercado": "Bahamas","preco":"2.6"},
{"nome":"Fermento em pó","supermercado": "Bahamas","preco":"1.93"},
{"nome":"Biscoitos","supermercado": "Bahamas","preco":"3.07"},
{"nome":"Chocolate","supermercado": "Bahamas","preco":"5.34"},
{"nome":"Sorvete","supermercado": "Bahamas","preco":"6.35"},
{"nome":"Cerveja","supermercado": "Bahamas","preco":"3.14"},
{"nome":"Vinho","supermercado": "Bahamas","preco":"10.79"},
{"nome":"Whisky","supermercado": "Bahamas","preco":"27.89"},
{"nome":"Leite condensado","supermercado": "Bahamas","preco":"3.83"},
{"nome":"Creme de leite","supermercado": "Bahamas","preco":"2.88"},
{"nome":"Achocolatado","supermercado": "Bahamas","preco":"4.25"},
{"nome":"Iogurte","supermercado": "Bahamas","preco":"2.62"},
{"nome":"Doce de leite","supermercado": "Bahamas","preco":"4.11"},
{"nome":"Biscoito recheado","supermercado": "Bahamas","preco":"2.93"},
{"nome":"Queijo ralado","supermercado": "Bahamas","preco":"5.03"},
{"nome":"Molho de tomate","supermercado": "Bahamas","preco":"2.29"},
{"nome":"Maionese","supermercado": "Bahamas","preco":"3.53"},
{"nome":"Ketchup","supermercado": "Bahamas","preco":"1.69"},
{"nome":"Mostarda","supermercado": "Bahamas","preco":"1.87"},
{"nome":"Catchup","supermercado": "Bahamas","preco":"1.94"},
{"nome":"Geléia","supermercado": "Bahamas","preco":"3.08"},
{"nome":"Margarina","supermercado": "Bahamas","preco":"1.81"},
{"nome":"Sabonete","supermercado": "Bahamas","preco":"1.12"},
{"nome":"Shampoo","supermercado": "Bahamas","preco":"4.84"},
{"nome":"Condicionador","supermercado": "Bahamas","preco":"4.75"},
{"nome":"Escova de dentes","supermercado": "Bahamas","preco":"2.34"},
{"nome":"Pasta de dente","supermercado": "Bahamas","preco":"2.02"},
{"nome":"Papel higiênico","supermercado": "Bahamas","preco":"3.75"},
{"nome":"Sabão em pó","supermercado": "Bahamas","preco":"5.63"},
{"nome":"Amaciante de roupas","supermercado": "Bahamas","preco":"3.76"},
{"nome":"Detergente","supermercado": "Bahamas","preco":"1.85"},
{"nome":"Esponja de cozinha","supermercado": "Bahamas","preco":"1.05"},
{"nome":"Desodorante","supermercado": "Bahamas","preco":"4.62"},
{"nome":"Perfume","supermercado": "Bahamas","preco":"23.56"},
{"nome":"Talco","supermercado": "Bahamas","preco":"2.6"},
{"nome":"Lâmina de barbear","supermercado": "Bahamas","preco":"4.06"},
{"nome":"Fio dental","supermercado": "Bahamas","preco":"1.82"},
{"nome":"Algodão","supermercado": "Bahamas","preco":"0.93"},
{"nome":"Pilhas","supermercado": "Bahamas","preco":"2.96"},
{"nome":"Lâmpadas","supermercado": "Bahamas","preco":"3.65"},
{"nome":"Vela","supermercado": "Bahamas","preco":"0.91"},
{"nome":"Fósforos","supermercado": "Bahamas","preco":"0.96"},
{"nome":"Enlatados","supermercado": "Bahamas","preco":"3.76"},
{"nome":"Salgadinhos","supermercado": "Bahamas","preco":"4.64"},
{"nome":"Pipoca","supermercado": "Bahamas","preco":"1.91"},
{"nome":"Queijo coalho","supermercado": "Bahamas","preco":"6.67"},
{"nome":"Mortadela","supermercado": "Bahamas","preco":"5.69"},
{"nome":"Salsicha","supermercado": "Bahamas","preco":"3.82"},
{"nome":"Linguiça","supermercado": "Bahamas","preco":"4.97"},
{"nome":"Salame","supermercado": "Bahamas","preco":"7.5"},
{"nome":"Peito de peru","supermercado": "Bahamas","preco":"8.69"},
{"nome":"Picanha","supermercado": "Bahamas","preco":"17.2"},
{"nome":"Filé de peixe","supermercado": "Bahamas","preco":"11.59"},
{"nome":"Atum","supermercado": "Bahamas","preco":"5.31"},
{"nome":"Salmão","supermercado": "Bahamas","preco":"13.14"},
{"nome":"Camarão","supermercado": "Bahamas","preco":"14.05"},
{"nome":"Ostras","supermercado": "Bahamas","preco":"16.79"},
{"nome":"Amêndoas","supermercado": "Bahamas","preco":"7.29"},
{"nome":"Castanhas","supermercado": "Bahamas","preco":"8.78"},
{"nome":"Nozes","supermercado": "Bahamas","preco":"8.05"},
{"nome":"Pistaches","supermercado": "Bahamas","preco":"10.89"},
{"nome":"Suco em pó","supermercado": "Bahamas","preco":"1.55"},
{"nome":"Chá","supermercado": "Bahamas","preco":"3.14"},
{"nome":"Massa de pastel","supermercado": "Bahamas","preco":"2.18"},
{"nome":"Molho de pimenta","supermercado": "Bahamas","preco":"1.58"},
{"nome":"Batata chips","supermercado": "Bahamas","preco":"3.29"},
{"nome":"Cereais","supermercado": "Bahamas","preco":"5.77"},
{"nome":"Granola","supermercado": "Bahamas","preco":"4.8"},
{"nome":"Barra de cereal","supermercado": "Bahamas","preco":"1.78"},
{"nome":"Geleia de mocotó","supermercado": "Bahamas","preco":"2.68"},
{"nome":"Feijão preto","supermercado": "Bahamas","preco":"3.68"},
{"nome":"Feijão carioca","supermercado": "Bahamas","preco":"3.55"},
{"nome":"Milho enlatado","supermercado": "Bahamas","preco":"2.66"},
{"nome":"Ervilha enlatada","supermercado": "Bahamas","preco":"2.38"},
{"nome":"Lentilha enlatada","supermercado": "Bahamas","preco":"2.41"},
{"nome":"Amido de milho","supermercado": "Bahamas","preco":"2.51"},
{"nome":"Farinha de mandioca","supermercado": "Bahamas","preco":"2.24"},
{"nome":"Farofa pronta","supermercado": "Bahamas","preco":"3.38"},
{"nome":"Molho shoyu","supermercado": "Bahamas","preco":"3.18"},
{"nome":"Azeite de oliva","supermercado": "Bahamas","preco":"5.74"},
{"nome":"Vinagre","supermercado": "Bahamas","preco":"1.34"},
{"nome":"Azeitonas","supermercado": "Bahamas","preco":"3.23"},
{"nome":"Palmito","supermercado": "Bahamas","preco":"4.58"},
{"nome":"Pepino em conserva","supermercado": "Bahamas","preco":"2.43"},
{"nome":"Abobrinha","supermercado": "Bahamas","preco":"1.36"},
{"nome":"Berinjela","supermercado": "Bahamas","preco":"1.77"},
{"nome":"Repolho","supermercado": "Bahamas","preco":"0.92"},
{"nome":"Milho verde","supermercado": "Bahamas","preco":"2.58"},
{"nome":"Couve-flor","supermercado": "Bahamas","preco":"3.41"},
{"nome":"Brócolis","supermercado": "Bahamas","preco":"3.39"},
{"nome":"Alho","supermercado": "Bahamas","preco":"1.25"},
{"nome":"Salsa","supermercado": "Bahamas","preco":"0.86"},
{"nome":"Hortelã","supermercado": "Bahamas","preco":"0.98"},
{"nome":"Manjericão","supermercado": "Bahamas","preco":"1.62"},
{"nome":"Alecrim","supermercado": "Bahamas","preco":"0.88"},
{"nome":"Salsinha","supermercado": "Bahamas","preco":"1.03"},
{"nome":"Orégano","supermercado": "Bahamas","preco":"1.58"},
{"nome":"Pimenta-do-reino","supermercado": "Bahamas","preco":"2.02"},
{"nome":"Pimenta vermelha","supermercado": "Bahamas","preco":"2.32"},
{"nome":"Mel","supermercado": "Bahamas","preco":"3.89"},
{"nome":"Chocolate em pó","supermercado": "Bahamas","preco":"3.01"},
{"nome":"Gelatina","supermercado": "Bahamas","preco":"0.94"},
{"nome":"Leite em pó","supermercado": "Bahamas","preco":"5.03"},
{"nome":"Cuscuz","supermercado": "Bahamas","preco":"2.39"},
{"nome":"Iogurte de frutas","supermercado": "Bahamas","preco":"2.33"},
{"nome":"Chantilly","supermercado": "Bahamas","preco":"3.17"},
{"nome":"Pudim","supermercado": "Bahamas","preco":"2.55"},
{"nome":"Gelatina em pó","supermercado": "Bahamas","preco":"0.97"},
{"nome":"Bala","supermercado": "Bahamas","preco":"0.55"},
{"nome":"Pipoca doce","supermercado": "Bahamas","preco":"1.77"},
{"nome":"Amendoim","supermercado": "Bahamas","preco":"1.41"},
{"nome":"Salgadinho de milho","supermercado": "Bahamas","preco":"3.81"},
{"nome":"Salgadinho de queijo","supermercado": "Bahamas","preco":"3.5"},
{"nome":"Salgadinho de cebola","supermercado": "Bahamas","preco":"3.58"},
{"nome":"Salgadinho de churrasco","supermercado": "Bahamas","preco":"3.77"},
{"nome":"Salgadinho de bacon","supermercado": "Bahamas","preco":"3.22"},
{"nome":"Salgadinho de pimenta","supermercado": "Bahamas","preco":"3.33"},
{"nome":"Salgadinho de limão","supermercado": "Bahamas","preco":"3.59"},
{"nome":"Salgadinho de salsa","supermercado": "Bahamas","preco":"3.29"},
{"nome":"Salgadinho de alho","supermercado": "Bahamas","preco":"3.45"},
{"nome":"Salgadinho de ervas","supermercado": "Bahamas","preco":"3.31"},
{"nome":"Salgadinho de queijo e cebola","supermercado": "Bahamas","preco":"3.47"},
{"nome":"Salgadinho de presunto e queijo","supermercado": "Bahamas","preco":"4.43"},
{"nome":"Arroz","supermercado": "APAS","preco":"5.99"},
{"nome":"Feijão","supermercado": "APAS","preco":"4.49"},
{"nome":"Macarrão","supermercado": "APAS","preco":"2.79"},
{"nome":"Leite","supermercado": "APAS","preco":"4.49"},
{"nome":"Ovos","supermercado": "APAS","preco":"2.49"},
{"nome":"Pão","supermercado": "APAS","preco":"3.99"},
{"nome":"Manteiga","supermercado": "APAS","preco":"6.99"},
{"nome":"Queijo","supermercado": "APAS","preco":"9.49"},
{"nome":"Presunto","supermercado": "APAS","preco":"5.99"},
{"nome":"Frango","supermercado": "APAS","preco":"8.49"},
{"nome":"Carne moída","supermercado": "APAS","preco":"12.49"},
{"nome":"Alface","supermercado": "APAS","preco":"1.39"},
{"nome":"Tomate","supermercado": "APAS","preco":"2.79"},
{"nome":"Cebola","supermercado": "APAS","preco":"1.09"},
{"nome":"Batata","supermercado": "APAS","preco":"2.79"},
{"nome":"Cenoura","supermercado": "APAS","preco":"1.59"},
{"nome":"Banana","supermercado": "APAS","preco":"1.59"},
{"nome":"Maçã","supermercado": "APAS","preco":"3.09"},
{"nome":"Laranja","supermercado": "APAS","preco":"2.09"},
{"nome":"Mamão","supermercado": "APAS","preco":"1.69"},
{"nome":"Abacaxi","supermercado": "APAS","preco":"4.29"},
{"nome":"Morango","supermercado": "APAS","preco":"5.49"},
{"nome":"Melancia","supermercado": "APAS","preco":"5.49"},
{"nome":"Suco de laranja","supermercado": "APAS","preco":"3.29"},
{"nome":"Refrigerante","supermercado": "APAS","preco":"4.49"},
{"nome":"Água mineral","supermercado": "APAS","preco":"0.89"},
{"nome":"Café","supermercado": "APAS","preco":"6.49"},
{"nome":"Açúcar","supermercado": "APAS","preco":"2.09"},
{"nome":"Sal","supermercado": "APAS","preco":"0.79"},
{"nome":"Óleo de soja","supermercado": "APAS","preco":"4.99"},
{"nome":"Farinha de trigo","supermercado": "APAS","preco":"2.29"},
{"nome":"Fermento em pó","supermercado": "APAS","preco":"1.79"},
{"nome":"Biscoitos","supermercado": "APAS","preco":"3.99"},
{"nome":"Chocolate","supermercado": "APAS","preco":"4.49"},
{"nome":"Sorvete","supermercado": "APAS","preco":"6.49"},
{"nome":"Cerveja","supermercado": "APAS","preco":"4.49"},
{"nome":"Vinho","supermercado": "APAS","preco":"9.49"},
{"nome":"Whisky","supermercado": "APAS","preco":"28.99"},
{"nome":"Leite condensado","supermercado": "APAS","preco":"4.49"},
{"nome":"Creme de leite","supermercado": "APAS","preco":"2.49"},
{"nome":"Achocolatado","supermercado": "APAS","preco":"4.99"},
{"nome":"Iogurte","supermercado": "APAS","preco":"2.29"},
{"nome":"Doce de leite","supermercado": "APAS","preco":"4.99"},
{"nome":"Biscoito recheado","supermercado": "APAS","preco":"4.49"},
{"nome":"Queijo ralado","supermercado": "APAS","preco":"4.79"},
{"nome":"Molho de tomate","supermercado": "APAS","preco":"2.29"},
{"nome":"Maionese","supermercado": "APAS","preco":"3.49"},
{"nome":"Ketchup","supermercado": "APAS","preco":"2.19"},
{"nome":"Mostarda","supermercado": "APAS","preco":"2.19"},
{"nome":"Catchup","supermercado": "APAS","preco":"1.79"},
{"nome":"Geléia","supermercado": "APAS","preco":"4.49"},
{"nome":"Margarina","supermercado": "APAS","preco":"2.19"},
{"nome":"Sabonete","supermercado": "APAS","preco":"0.89"},
{"nome":"Shampoo","supermercado": "APAS","preco":"5.49"},
{"nome":"Condicionador","supermercado": "APAS","preco":"5.49"},
{"nome":"Escova de dentes","supermercado": "APAS","preco":"2.79"},
{"nome":"Pasta de dente","supermercado": "APAS","preco":"1.79"},
{"nome":"Papel higiênico","supermercado": "APAS","preco":"4.49"},
{"nome":"Sabão em pó","supermercado": "APAS","preco":"6.49"},
{"nome":"Amaciante de roupas","supermercado": "APAS","preco":"4.49"},
{"nome":"Detergente","supermercado": "APAS","preco":"2.19"},
{"nome":"Esponja de cozinha","supermercado": "APAS","preco":"0.89"},
{"nome":"Desodorante","supermercado": "APAS","preco":"4.99"},
{"nome":"Perfume","supermercado": "APAS","preco":"23.99"},
{"nome":"Talco","supermercado": "APAS","preco":"2.79"},
{"nome":"Lâmina de barbear","supermercado": "APAS","preco":"4.49"},
{"nome":"Fio dental","supermercado": "APAS","preco":"2.19"},
{"nome":"Algodão","supermercado": "APAS","preco":"0.89"},
{"nome":"Pilhas","supermercado": "APAS","preco":"2.79"},
{"nome":"Lâmpadas","supermercado": "APAS","preco":"3.99"},
{"nome":"Vela","supermercado": "APAS","preco":"0.89"},
{"nome":"Fósforos","supermercado": "APAS","preco":"0.89"},
{"nome":"Enlatados","supermercado": "APAS","preco":"3.99"},
{"nome":"Salgadinhos","supermercado": "APAS","preco":"5.49"},
{"nome":"Pipoca","supermercado": "APAS","preco":"1.79"},
{"nome":"Queijo coalho","supermercado": "APAS","preco":"6.49"},
{"nome":"Mortadela","supermercado": "APAS","preco":"5.49"},
{"nome":"Salsicha","supermercado": "APAS","preco":"4.49"},
{"nome":"Linguiça","supermercado": "APAS","preco":"5.49"},
{"nome":"Salame","supermercado": "APAS","preco":"7.49"},
{"nome":"Peito de peru","supermercado": "APAS","preco":"8.49"},
{"nome":"Picanha","supermercado": "APAS","preco":"17.49"},
{"nome":"Filé de peixe","supermercado": "APAS","preco":"10.49"},
{"nome":"Atum","supermercado": "APAS","preco":"5.49"},
{"nome":"Salmão","supermercado": "APAS","preco":"12.49"},
{"nome":"Camarão","supermercado": "APAS","preco":"14.49"},
{"nome":"Ostras","supermercado": "APAS","preco":"17.49"},
{"nome":"Amêndoas","supermercado": "APAS","preco":"6.49"},
{"nome":"Castanhas","supermercado": "APAS","preco":"8.49"},
{"nome":"Nozes","supermercado": "APAS","preco":"7.49"},
{"nome":"Pistaches","supermercado": "APAS","preco":"11.49"},
{"nome":"Suco em pó","supermercado": "APAS","preco":"1.39"},
{"nome":"Chá","supermercado": "APAS","preco":"2.79"},
{"nome":"Massa de pastel","supermercado": "APAS","preco":"1.79"},
{"nome":"Molho de pimenta","supermercado": "APAS","preco":"1.39"},
{"nome":"Batata chips","supermercado": "APAS","preco":"4.49"},
{"nome":"Cereais","supermercado": "APAS","preco":"5.99"},
{"nome":"Granola","supermercado": "APAS","preco":"5.49"},
{"nome":"Barra de cereal","supermercado": "APAS","preco":"1.79"},
{"nome":"Geleia de mocotó","supermercado": "APAS","preco":"3.49"},
{"nome":"Feijão preto","supermercado": "APAS","preco":"3.99"},
{"nome":"Feijão carioca","supermercado": "APAS","preco":"4.49"},
{"nome":"Milho enlatado","supermercado": "APAS","preco":"2.79"},
{"nome":"Ervilha enlatada","supermercado": "APAS","preco":"2.79"},
{"nome":"Lentilha enlatada","supermercado": "APAS","preco":"2.79"},
{"nome":"Amido de milho","supermercado": "APAS","preco":"2.79"},
{"nome":"Farinha de mandioca","supermercado": "APAS","preco":"2.79"},
{"nome":"Farofa pronta","supermercado": "APAS","preco":"4.49"},
{"nome":"Molho shoyu","supermercado": "APAS","preco":"4.49"},
{"nome":"Azeite de oliva","supermercado": "APAS","preco":"5.49"},
{"nome":"Vinagre","supermercado": "APAS","preco":"1.39"},
{"nome":"Azeitonas","supermercado": "APAS","preco":"4.49"},
{"nome":"Palmito","supermercado": "APAS","preco":"5.49"},
{"nome":"Pepino em conserva","supermercado": "APAS","preco":"2.79"},
{"nome":"Abobrinha","supermercado": "APAS","preco":"1.39"},
{"nome":"Berinjela","supermercado": "APAS","preco":"1.79"},
{"nome":"Repolho","supermercado": "APAS","preco":"0.89"},
{"nome":"Milho verde","supermercado": "APAS","preco":"2.79"},
{"nome":"Couve-flor","supermercado": "APAS","preco":"4.49"},
{"nome":"Brócolis","supermercado": "APAS","preco":"4.49"},
{"nome":"Alho","supermercado": "APAS","preco":"1.19"},
{"nome":"Salsa","supermercado": "APAS","preco":"0.89"},
{"nome":"Hortelã","supermercado": "APAS","preco":"0.89"},
{"nome":"Manjericão","supermercado": "APAS","preco":"1.29"},
{"nome":"Alecrim","supermercado": "APAS","preco":"0.89"},
{"nome":"Salsinha","supermercado": "APAS","preco":"0.89"},
{"nome":"Orégano","supermercado": "APAS","preco":"1.29"},
{"nome":"Pimenta-do-reino","supermercado": "APAS","preco":"1.79"},
{"nome":"Pimenta vermelha","supermercado": "APAS","preco":"2.79"},
{"nome":"Mel","supermercado": "APAS","preco":"4.49"},
{"nome":"Chocolate em pó","supermercado": "APAS","preco":"3.49"},
{"nome":"Gelatina","supermercado": "APAS","preco":"1.29"},
{"nome":"Leite em pó","supermercado": "APAS","preco":"5.49"},
{"nome":"Cuscuz","supermercado": "APAS","preco":"2.79"},
{"nome":"Iogurte de frutas","supermercado": "APAS","preco":"2.79"},
{"nome":"Chantilly","supermercado": "APAS","preco":"3.49"},
{"nome":"Pudim","supermercado": "APAS","preco":"2.79"},
{"nome":"Gelatina em pó","supermercado": "APAS","preco":"0.89"},
{"nome":"Bala","supermercado": "APAS","preco":"0.39"},
{"nome":"Pipoca doce","supermercado": "APAS","preco":"1.79"},
{"nome":"Amendoim","supermercado": "APAS","preco":"1.29"},
{"nome":"Salgadinho de milho","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de queijo","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de cebola","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de churrasco","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de bacon","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de pimenta","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de limão","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de salsa","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de alho","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de ervas","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de queijo e cebola","supermercado": "APAS","preco":"4.49"},
{"nome":"Salgadinho de presunto e queijo","supermercado": "APAS","preco":"5.49"}

      ];
      
      for (const product of products) {
        await client.index({
          index: 'produto',
          type: 'type_produto',
          body: product,
        });
      }
      
    // const result = await client.index({
    //     index: 'produto',
    //     type: 'type_produto',
    //     body: {
    //         nome: 'Coca Cola lata zero 350ml',
    //         supermercado: 'dale',
    //         preco: 5
    //     },
        
    // })

    return res.status(200).send({
        message: "produtos cadastrados com sucesso",
    });
}  
    

exports.findAll = async(req, res) =>{


    const result = await client.search({
        index: 'produto',
        body: {
            query: {
                match : {
                    nome : {
                        query : "Pepsi 350ml",
                        fuzziness: 1,

                        operator: "and"
                    }
                }
            } 
        } 
    })

    return res.status(200).send({
        message: result.body.hits.hits,
    });
}  
    

// elasticdump \ --input=http://localhost:9200/produto/ --output=EmployeeData.json \ --type=data
// elasticdump --bulk=true --input=EmployeeData.json --output=http://localhost:9200/produto
